### ISSUE TITLE
Repo provisioning not quite ready yet

### ISSUE THREAD

**Issue by rtholmes** [ubccpsc310/classy#108]
@nickbradley noticed some branches weren't quite right when he provisioned a repo late in 23W2.

**Comment by rtholmes** [comment]
Going to need more investigation. @nickbradley do you remember if it was extra branches in the provisioned repo or that the branch that was imported wasn't re-named to main?

**Comment by nickbradley** [comment]
IIRC all the branches were just copied directly from the source repo verbatim. So there were both too many branches in the provisioned repo and none of them were renamed to main. Branch protection was not set either.

**Comment by rtholmes** [comment]
This has been fixed today.
