### ISSUE TITLE
Move cluster to custom

### ISSUE THREAD

**Issue by LucasZamprogno** [ubccpsc310/classy#34]
Cluster is currently an optional param in grade report, didn't know that would get upstreamed so we should just use custom

**Comment by braxtonhall** [comment]
Current roadblock:
As seen [here](https://github.com/ubccpsc310/classy/blob/51ca09a90faec5d1ebc4b3f9cbac3b414ff42231/packages/portal/backend/src/controllers/AdminController.ts#L329) the custom field is not sent to the frontend where the cluster is used.

Some possible options:
- send the custom field to the front end
- if custom is too big for some courses, set up a mechanism for selecting fields from custom to go to the front end. this mechanism should be configurable in the CustomCourseController
- let the cluster remain in place

**Comment by braxtonhall** [comment]
This can now be easily achieved using [`CustomCourseController:: forwardCustomFields(..)`](https://github.com/ubccpsc310/classy/blob/591538332cbae242c1c68f00251199281b57a151/packages/portal/backend/src/custom/CustomCourseController.ts#L227). It would probably look something like this:
```typescript
const cc = await Factory.getCourseController(this.gh);
const custom = cc.forwardCustomFields(resultSummary.custom, TransportKind.AUTOTEST_DASHBOARD);
const resultTrans: AutoTestDashboardTransport = {
    ...resultSummary,
    testPass:  testPass,
    testFail:  testFail,
    testError: testError,
    testSkip:  testSkip,
    custom: custom
};
```
